# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 22:54
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20171110_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='coords',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
