# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 22:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_coords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='post',
            name='lon',
        ),
    ]
